# Generated by Django 2.1.7 on 2019-02-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldoption',
            name='value',
            field=models.TextField(unique=True),
        ),
    ]
