# Generated by Django 2.1.7 on 2019-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldattempt',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
