# Generated by Django 2.1.7 on 2019-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_auto_20190301_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfieldattempt',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
